from rich.theme import Theme

class Themer:
    THEMES = {
        'classic': Theme({
            'map_wall': 'white on black',
            'map_floor': 'black on black',
            'map_player': 'bold bright_cyan on black',
            'map_monster': 'bold bright_red on black',
            'map_item': 'bold bright_yellow on black',
            'map_door': 'bold yellow on black',
            'map_exit': 'bold bright_green on black',
            'map_trap': 'bold magenta on black',
            'map_fog': 'dim black on black',
            'bar_hp': 'bright_red',
            'bar_mp': 'bright_blue',
            'bar_bg': 'dim black',
            'status_text': 'white',
            'log_text': 'white',
            'highlight': 'bold bright_yellow',
            'menu_selected': 'black on bright_cyan',
            'menu_normal': 'white',
            'title': 'bold bright_magenta',
            'gold': 'bold bright_yellow',
        }),
        'dark': Theme({
            'map_wall': 'dim grey23 on grey11',
            'map_floor': 'grey19 on grey11',
            'map_player': 'bold bright_cyan on grey11',
            'map_monster': 'bold red on grey11',
            'map_item': 'bold yellow on grey11',
            'map_door': 'bold gold3 on grey11',
            'map_exit': 'bold spring_green3 on grey11',
            'map_trap': 'bold purple on grey11',
            'map_fog': 'grey7 on grey11',
            'bar_hp': 'red',
            'bar_mp': 'dodger_blue2',
            'bar_bg': 'grey19',
            'status_text': 'grey82',
            'log_text': 'grey66',
            'highlight': 'bold bright_yellow',
            'menu_selected': 'grey11 on cyan',
            'menu_normal': 'grey82',
            'title': 'bold dark_orange',
            'gold': 'bold gold1',
        }),
        'green': Theme({
            'map_wall': 'bold green on black',
            'map_floor': 'black on black',
            'map_player': 'bold bright_green on black',
            'map_monster': 'bold red on black',
            'map_item': 'bold yellow on black',
            'map_door': 'bold green on black',
            'map_exit': 'bold bright_green on black',
            'map_trap': 'bold magenta on black',
            'map_fog': 'black on black',
            'bar_hp': 'bright_green',
            'bar_mp': 'bright_blue',
            'bar_bg': 'black',
            'status_text': 'green',
            'log_text': 'green',
            'highlight': 'bold bright_green',
            'menu_selected': 'black on bright_green',
            'menu_normal': 'green',
            'title': 'bold bright_green',
            'gold': 'bold yellow',
        }),
        'warm': Theme({
            'map_wall': 'bright_black on black',
            'map_floor': 'grey37 on black',
            'map_player': 'bold bright_yellow on black',
            'map_monster': 'bold bright_red on black',
            'map_item': 'bold yellow on black',
            'map_door': 'bold yellow on black',
            'map_exit': 'bold bright_green on black',
            'map_trap': 'bold bright_magenta on black',
            'map_fog': 'black on black',
            'bar_hp': 'bright_red',
            'bar_mp': 'bright_blue',
            'bar_bg': 'grey11',
            'status_text': 'bright_white',
            'log_text': 'white',
            'highlight': 'bold yellow',
            'menu_selected': 'black on yellow',
            'menu_normal': 'white',
            'title': 'bold bright_yellow',
            'gold': 'bold yellow',
        }),
    }
    
    @classmethod
    def get(cls, name: str = 'classic') -> Theme:
        return cls.THEMES.get(name, cls.THEMES['classic'])
        
    @classmethod
    def list(cls) -> list[str]:
        return list(cls.THEMES.keys())
